---
languages:
  JavaScript: true
  Python: true
exclude_paths:
- "hourglass_site/static/hourglass_site/tests/*"
- "hourglass_site/static/hourglass_site/js/vendor/*"
- "hourglass_site/static/hourglass_site/style/vendor/*"
- "hourglass_site/static_source/js/vendor/*"
- "hourglass_site/static_source/style/vendor/*"
- "hourglass_site/static_source/style/skeleton/*"
- "styleguide/static/styleguide/vendor/*"
- "contracts/migrations/*"
- "selenium_tests/*"
engines:
  eslint:
    enabled: true
    channel: "eslint-2"
    checks:
      import/no-unresolved:
        enabled: false
  csslint:
    enabled: true
  pep8:
    enabled: true
ratings:
  paths:
  - "**.py"
