language: python
python:
- 2.7
- 3.4

install:
- "pip install -r requirements.txt"
- "pip install -r requirements.txt"

# install python 2 requirements iff we're in py2
before_script:
- "[ `python -c 'import sys; print sys.version_info.major'` == 2 ] && pip install -r requirements_python2.txt"

script: make test
