language: python
python:
  - 3.4

addons:
  postgresql: 9.3

matrix:
  # finish on the first failure
  fast_finish: true

install:
  - pip install -r requirements.txt

script:
  - cp hourglass/local_settings{.travis,}.py
  - phantomjs --version
  - make test

# don't spam us with emails
notifications:
  email: false
