language: python
python:
- 3.4
addons:
  postgresql: 9.3
  sauce_connect: true
matrix:
  fast_finish: true
services:
- redis-server
before_install:
- pip install codeclimate-test-reporter
- npm install -g gulp-cli
- npm --version
- node --version
after_success:
- codeclimate-test-reporter
install:
- pip install -r requirements-dev.txt
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
- npm install
script:
- phantomjs --version
- python manage.py ultratest flake8
- echo "For details on why we're ignoring selenium tests, see https://github.com/18F/calc/issues/330"
- bandit -r .
- py.test --ignore=frontend/tests/test_selenium.py --cov
env:
  global:
  - TRAVIS_NODE_VERSION=6.5.0
  - PHANTOMJS_TIMEOUT=15
  - DEBUG=yup
  - DATABASE_URL=postgres://postgres@localhost/hourglass

  # These environment variables affect the running of Webdriver/Selenium
  # tests. Note that if we're not in a trusted environment (e.g. a PR
  # is being issued from an untrusted fork), we will default to using
  # PhantomJS locally, rather than a real-world browser via Sauce Labs.
  - DJANGO_LIVE_TEST_SERVER_ADDRESS=127.0.0.1:8000
  - WD_TESTING_BROWSER="internet explorer"
  - WD_TESTING_BROWSER_VERSION=11.103
  - WD_JOB_VISIBILITY=public
  - WD_SOCKET_TIMEOUT=60
  - SAUCE_USERNAME=atulvarma
  - secure: "RbgG35nc1SHgjdxVbGUDlumePeR/+dXq5fMbfTXOW8uFYw5kGh75px2KdFDkL1JIA1vbfxyNFm09x32uXMcHsBKu9fJS7xbpMrRDbJoV2wVy5wd6qtvZ7yFbR87Fqo3/tuGu13jNNDvUgKjpUlrzLZKaL7qvv5Gd7CVhkySUa1o="
deploy:
  edge: true
  skip_cleanup: true
  provider: cloudfoundry
  username: deploy-hourglass
  password:
    secure: "dHsbCYyIb6GVhXioJvKaiNNcPfZuHcOKH8Ojci6EANC4gkxh3Xgtxg/fL/0I5twNM1NQFB7ERlzcsF/8f3FbhdXPYqRoTtgY4ej2t/v6POHHbNaaE9zDWe6z0jtGUWgnrwlsmv0urFigYxTBLgydtmps988/iEgNf+L0C2SjnvQ="
  api: https://api.cloud.gov
  organization: oasis
  space: calc-dev
  manifest: manifests/manifest-staging.yml
  on:
    branch: develop
sudo: required
