language: python
python:
- 2.7
- 3.4

install:
- "pip install -r requirements.txt"

matrix:
  # finish on the first failure
  fast_finish: true
  include:
    # install python 2 requirements iff we're in py2
    - python: "2.7"
      before_script: "pip install -r requirements_python2.txt"

script:
  - make test
