app:
  build: .
  links:
    - db
    - redis
  environment:
    - DDM_HOST_USER=calc_user
    - PYTHONUNBUFFERED=yup
    - DATABASE_URL=postgres://calc_user@db/calc
    - REDIS_URL=redis://redis:6379/0
  command: sh -c "python manage.py collectstatic --noinput ; gunicorn -b :${DOCKER_EXPOSED_PORT} hourglass.wsgi:application"
  ports:
    - "${DOCKER_EXPOSED_PORT}:${DOCKER_EXPOSED_PORT}"
db:
  image: postgres:9.4
  environment:
    - POSTGRES_DB=calc
    - POSTGRES_USER=calc_user
redis:
  image: redis:3.0.7-alpine
rq_worker:
  build: .
  links:
    - db
    - redis
  environment:
    - DDM_HOST_USER=calc_user
    - PYTHONUNBUFFERED=yup
    - DATABASE_URL=postgres://calc_user@db/calc
    - REDIS_URL=redis://redis:6379/0
  command: sh -c "python manage.py rqworker"
