app:
  build: .
  links:
    - db
  working_dir: /calc
  entrypoint: python /calc/docker_django_management.py
  environment:
    - DDM_HOST_USER=calc_user
    - DATABASE_URL=postgres://calc_user@db/calc
db:
  image: postgres:9.4
  environment:
    - POSTGRES_DB=calc
    - POSTGRES_USER=calc_user
