app:
  volumes:
    - .:/calc
  command: python manage.py runserver 0.0.0.0:${DOCKER_EXPOSED_PORT}
sass:
  build: .
  volumes:
    - .:/calc
  working_dir: /calc/hourglass_site/static/hourglass_site
  entrypoint: python /calc/docker_django_management.py
  command: make watch-style
