app:
  build: .
  links:
    - db
  environment:
    - DDM_HOST_USER=calc_user
    - PYTHONUNBUFFERED=yup
    - DATABASE_URL=postgres://calc_user@db/calc
  command: sh -c "python manage.py collectstatic --noinput ; waitress-serve --port=${DOCKER_EXPOSED_PORT} hourglass.wsgi:application"
  ports:
    - "${DOCKER_EXPOSED_PORT}:${DOCKER_EXPOSED_PORT}"
db:
  image: postgres:9.4
  environment:
    - POSTGRES_DB=calc
    - POSTGRES_USER=calc_user
