app:
  build: .
  links:
    - db
  working_dir: /calc
  entrypoint: python /calc/docker_django_management.py
  environment:
    - DDM_HOST_USER=calc_user
    - DDM_IS_RUNNING_IN_DOCKER=yup
    - PYTHONUNBUFFERED=yup
    - DATABASE_URL=postgres://calc_user@db/calc
  command: sh -c "python manage.py collectstatic --noinput ; waitress-serve --port=${DOCKER_EXPOSED_PORT} hourglass.wsgi:application"
  ports:
    - "${DOCKER_EXPOSED_PORT}:${DOCKER_EXPOSED_PORT}"
db:
  image: postgres:9.4
  environment:
    - POSTGRES_DB=calc
    - POSTGRES_USER=calc_user
