---
services:
- calc-db
- calc-env
- calc-redis
applications:
- name: calc-prod-b
  host: calc-prod-b
  instances: 4
  memory: 1024M
  disk_quota: 1024M
  domain: apps.cloud.gov
  buildpack: python_buildpack
  command: bash cf.sh
  stack: cflinuxfs2
  timeout: 180
  env:
    NEW_RELIC_APP_NAME: "CALC (production)"
    NEW_RELIC_CONFIG_FILE: "newrelic.ini"
    NEW_RELIC_ENV: "production"
    NEW_RELIC_LOG: "stdout"
- name: calc-rqworker-b
  no-route: true
  instances: 1
  memory: 256M
  buildpack: python_buildpack
  command: python manage.py rqworker default
  stack: cflinuxfs2
  timeout: 180
  env:
    DISABLE_COLLECTSTATIC: "1"
- name: calc-rqscheduler-b
  no-route: true
  instances: 1
  memory: 256M
  buildpack: python_buildpack
  command: python manage.py rqscheduler
  stack: cflinuxfs2
  timeout: 180
  env:
    IS_RQ_SCHEDULER: "yup"
    DISABLE_COLLECTSTATIC: "1"
